version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: chatbox-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbox-next
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:123456@mysql:3306/chatbox_db
    volumes:
      - ./.env.production:/app/.env.production
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mysql:
    image: mysql:8.0
    container_name: chatbox-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=chatbox_db
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mysql_data:
