version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: chatbox-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt # SSL证书目录
    depends_on:
      - app
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  app:
    image: ${DOCKER_IMAGE:-registry.cn-hangzhou.aliyuncs.com/your-namespace/chatbox:latest}
    container_name: chatbox-next
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD:-123456}@mysql:3306/chatbox_db
    env_file:
      - .env.production
    depends_on:
      - mysql
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mysql:
    image: mysql:8.0
    container_name: chatbox-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456}
      - MYSQL_DATABASE=chatbox_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
